In [9]:
!wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE6nnn/GSE6613/matrix/GSE6613_series_matrix.txt.gz
!wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE72nnn/GSE72267/matrix/GSE72267_series_matrix.txt.gz
!wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE99nnn/GSE99039/matrix/GSE99039_series_matrix.txt.gz
!wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE57nnn/GSE57475/matrix/GSE57475_series_matrix.txt.gz
!wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE18nnn/GSE18838/matrix/GSE18838_series_matrix.txt.gz

--2026-03-03 07:25:22--  https://ftp.ncbi.nlm.nih.gov/geo/series/GSE6nnn/GSE6613/matrix/GSE6613_series_matrix.txt.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.12, 130.14.250.11, 130.14.250.13, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.12|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4417660 (4.2M) [application/x-gzip]
Saving to: ‘GSE6613_series_matrix.txt.gz.2’

GSE6613_series_matr 100%[===================>]   4.21M  2.24MB/s    in 1.9s

2026-03-03 07:25:25 (2.24 MB/s) - ‘GSE6613_series_matrix.txt.gz.2’ saved [4417660/4417660]

--2026-03-03 07:25:25--  https://ftp.ncbi.nlm.nih.gov/geo/series/GSE72nnn/GSE72267/matrix/GSE72267_series_matrix.txt.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.13, 130.14.250.10, 130.14.250.12, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7252003 (6.9M) [application/x-gzip]
Saving to: ‘GSE72267_series_matrix.txt.gz.2’

GSE72267_series_mat 100%[===================>]   6.92M  2.87MB/s    in 2.4s

2026-03-03 07:25:29 (2.87 MB/s) - ‘GSE72267_series_matrix.txt.gz.2’ saved [7252003/7252003]

--2026-03-03 07:25:29--  https://ftp.ncbi.nlm.nih.gov/geo/series/GSE99nnn/GSE99039/matrix/GSE99039_series_matrix.txt.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.10, 130.14.250.12, 130.14.250.13, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 63827685 (61M) [application/x-gzip]
Saving to: ‘GSE99039_series_matrix.txt.gz’

GSE99039_series_mat 100%[===================>]  60.87M  3.08MB/s    in 22s

2026-03-03 07:25:58 (2.82 MB/s) - ‘GSE99039_series_matrix.txt.gz’ saved [63827685/63827685]

--2026-03-03 07:25:59--  https://ftp.ncbi.nlm.nih.gov/geo/series/GSE57nnn/GSE57475/matrix/GSE57475_series_matrix.txt.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.31, 130.14.250.10, 130.14.250.12, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28146276 (27M) [application/x-gzip]
Saving to: ‘GSE57475_series_matrix.txt.gz’

GSE57475_series_mat 100%[===================>]  26.84M  8.05MB/s    in 3.3s

2026-03-03 07:26:03 (8.05 MB/s) - ‘GSE57475_series_matrix.txt.gz’ saved [28146276/28146276]

--2026-03-03 07:26:03--  https://ftp.ncbi.nlm.nih.gov/geo/series/GSE18nnn/GSE18838/matrix/GSE18838_series_matrix.txt.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.13, 130.14.250.10, 130.14.250.12, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2466071 (2.4M) [application/x-gzip]
Saving to: ‘GSE18838_series_matrix.txt.gz’

GSE18838_series_mat 100%[===================>]   2.35M  1.27MB/s    in 1.8s

2026-03-03 07:26:06 (1.27 MB/s) - ‘GSE18838_series_matrix.txt.gz’ saved [2466071/2466071]

In [10]:
import pandas as pd

gse72267 = pd.read_csv("/workspaces/Reasearch_Genomic/GSE72267_series_matrix.txt.gz", 
                       sep="\t", 
                       comment="!", 
                       index_col=0)

gse72267.head()

,GSM1859079,GSM1859080,GSM1859081,GSM1859082,GSM1859083,GSM1859084,GSM1859085,GSM1859086,GSM1859087,GSM1859088,...,GSM1859128,GSM1859129,GSM1859130,GSM1859131,GSM1859132,GSM1859133,GSM1859134,GSM1859135,GSM1859136,GSM1859137
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,7.349298,7.274405,6.719570,7.083267,7.452170,7.072315,7.051066,6.915191,6.724721,6.752708,...,7.220690,7.273062,6.348098,7.215291,7.158651,6.939362,6.953196,6.783862,7.508211,7.442646
1053_at,8.906082,8.997323,9.145367,8.947209,8.679888,9.021920,8.833503,8.996459,8.499686,9.113918,...,9.114221,8.149797,9.125882,8.945029,9.098237,8.231308,8.962738,8.335829,8.669423,9.209691
117_at,10.916643,11.173430,11.369026,11.274212,10.783615,11.126310,10.577591,11.064433,10.878215,11.542708,...,11.873479,11.157583,11.803321,11.393424,11.568479,11.679601,11.522308,11.012502,11.605217,12.168853
121_at,6.954244,6.334305,6.733312,7.096500,6.813166,6.610517,6.888822,6.995565,6.561855,7.064596,...,6.646920,6.713738,7.034526,6.822774,6.696431,6.798336,6.599626,6.271728,5.885947,6.800522
1255_g_at,2.702785,2.581031,2.469741,2.774409,2.642078,2.732572,2.646264,3.032687,2.642967,2.429493,...,2.782319,2.540955,2.672644,2.703629,2.577448,2.678776,2.649259,2.667041,2.651123,2.543898

In [12]:
import pandas as pd

gse18838 = pd.read_csv("/workspaces/Reasearch_Genomic/GSE18838_series_matrix.txt.gz", 
                       sep="\t", 
                       comment="!", 
                       index_col=0)

gse18838.head()

,GSM466881,GSM466882,GSM466883,GSM466884,GSM466885,GSM466886,GSM466887,GSM466888,GSM466889,GSM466890,...,GSM466899,GSM466900,GSM466901,GSM466902,GSM466903,GSM466904,GSM466905,GSM466906,GSM466907,GSM466908
ID_REF,,,,,,,,,,,,,,,,,,,,,
2315554,0.198854,0.185974,0.368369,0.146662,-0.108868,0.172206,0.178632,-0.178847,-0.372000,0.589589,...,0.183152,0.218286,-0.347655,-0.126924,-0.355657,0.004305,-0.026484,-0.098608,0.197506,-0.089535
2315633,0.017993,-0.061915,0.193141,0.132386,-0.116641,-0.153508,0.252429,-0.308616,-0.044634,0.301462,...,0.132710,0.210008,0.183928,0.046324,-0.189339,-0.039036,-0.344419,-0.021370,-0.103078,-0.017993
2315674,0.032141,-0.026187,0.069813,-0.011104,-0.310982,0.065543,0.155250,-0.194125,-0.479885,0.570751,...,0.012489,0.195573,-0.056979,-0.257612,-0.244293,-0.057919,-0.185382,-0.018640,0.222848,0.011103
2315739,0.084374,-0.090920,0.254175,0.165577,-0.077745,0.226318,-0.035566,-0.133929,-0.179715,0.209865,...,0.134899,0.369460,0.116252,-0.180081,-0.022703,0.127094,0.118353,-0.038901,-0.042691,0.022703
2315894,0.330791,-0.449820,0.535277,0.247803,-0.246867,0.508080,-0.369174,-0.104843,-0.668175,0.574317,...,0.464739,0.713002,0.081458,0.087032,-0.359743,-0.171490,-0.455570,0.028783,0.309707,0.101218

In [13]:
import pandas as pd

gse57475 = pd.read_csv("/workspaces/Reasearch_Genomic/GSE57475_series_matrix.txt.gz", 
                       sep="\t", 
                       comment="!", 
                       index_col=0)

gse57475.head()

,GSM1383302,GSM1383303,GSM1383304,GSM1383305,GSM1383306,GSM1383307,GSM1383308,GSM1383309,GSM1383310,GSM1383311,...,GSM1383434,GSM1383435,GSM1383436,GSM1383437,GSM1383438,GSM1383439,GSM1383440,GSM1383441,GSM1383442,GSM1383443
ID_REF,,,,,,,,,,,,,,,,,,,,,
ILMN_1343291,19386.71000,18275.98000,14168.47000,16967.16000,16206.89000,11676.81000,24149.64000,20011.84000,24623.72000,22796.53000,...,20216.04000,18545.56000,19166.32000,17046.97000,18715.27000,17594.92000,18133.83000,16812.62000,12298.89000,12646.39000
ILMN_1343295,2364.02400,2631.18000,2407.83300,2373.61300,2102.27900,1900.13000,2071.05800,2231.25300,1750.86000,1997.50300,...,2205.49800,1639.98500,1436.87000,1618.65400,1330.39000,1826.11000,1593.41000,2682.48600,2148.15600,2441.03500
ILMN_1651199,68.18906,85.30925,85.06847,90.32904,86.16512,99.22817,81.92728,83.01512,67.99200,58.44085,...,67.64046,73.61387,71.49722,58.50450,76.17118,60.61678,64.64003,54.86134,58.32230,61.84894
ILMN_1651209,94.21075,112.35280,122.56880,103.94660,96.40077,126.20420,81.36551,86.43821,78.54828,76.93077,...,85.32426,85.87455,58.81615,61.17813,78.79471,75.06206,76.23627,58.91056,82.63440,56.76226
ILMN_1651210,54.22152,74.91089,77.42303,86.46082,65.59376,91.13580,80.87245,66.45086,56.37646,60.58017,...,80.53565,72.78075,62.82432,62.68112,72.12399,50.82701,60.77827,47.18052,61.74317,61.74254

In [19]:
import pandas as pd

gse6613 = pd.read_csv("/workspaces/Reasearch_Genomic/GSE6613_series_matrix.txt.gz", 
                       sep="\t", 
                       comment="!", 
                       index_col=0)

gse6613.head()

,GSM153404,GSM153405,GSM153406,GSM153407,GSM153408,GSM153409,GSM153410,GSM153411,GSM153412,GSM153413,...,GSM153499,GSM153500,GSM153501,GSM153502,GSM153503,GSM153504,GSM153505,GSM153506,GSM153507,GSM153508
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,114.5,105.1,145.7,168.7,94.3,96.2,155.8,99.8,100.9,106.4,...,153.8,103.7,132.8,195.5,82.6,28.2,163.9,29.0,104.8,32.8
1053_at,64.4,58.4,52.5,45.4,51.3,50.7,42.2,6.7,44.0,55.5,...,44.0,70.5,61.9,52.2,61.2,67.6,101.9,46.8,74.9,78.1
117_at,206.3,179.8,192.0,263.6,211.9,149.5,157.3,216.6,230.5,224.1,...,268.9,48.6,193.6,132.5,165.5,146.0,291.4,246.2,251.2,210.0
121_at,507.0,497.8,346.3,430.7,485.5,437.6,424.1,678.7,434.1,592.8,...,403.6,559.1,569.7,532.8,525.7,603.9,479.7,271.9,506.1,270.4
1255_g_at,34.5,18.0,40.1,40.5,22.8,6.4,27.4,5.2,34.7,18.6,...,44.8,39.5,30.5,65.8,54.3,19.3,61.0,40.8,29.5,82.2

In [18]:
import pandas as pd

gse99039 = pd.read_csv("/workspaces/Reasearch_Genomic/GSE99039_series_matrix.txt.gz", 
                       sep="\t", 
                       comment="!", 
                       index_col=0)

gse99039.head()

,GSM2630758,GSM2630759,GSM2630760,GSM2630761,GSM2630762,GSM2630763,GSM2630764,GSM2630765,GSM2630766,GSM2630767,...,GSM2631306,GSM2631307,GSM2631308,GSM2631309,GSM2631310,GSM2631311,GSM2631312,GSM2631313,GSM2631314,GSM2631315
ID_REF,,,,,,,,,,,,,,,,,,,,,
1007_s_at,5.397,4.952,5.331,5.601,5.087,5.921,5.153,5.341,5.261,5.147,...,5.583,5.535,5.737,4.937,5.765,6.056,5.989,5.697,5.567,5.529
1053_at,5.199,5.198,4.970,5.816,5.443,5.430,5.243,5.167,5.324,5.489,...,5.775,5.004,5.672,5.415,5.195,5.282,5.228,5.528,5.706,5.078
117_at,8.327,8.589,8.629,9.628,9.449,9.230,9.269,9.095,9.184,8.623,...,8.426,7.061,6.771,8.691,7.073,7.325,8.567,6.844,8.511,8.458
121_at,7.042,6.935,7.701,6.909,7.284,7.153,6.850,7.541,6.918,6.714,...,7.192,7.326,7.319,6.702,7.747,7.712,7.743,7.468,7.526,7.673
1255_g_at,2.463,2.388,2.349,2.268,2.407,2.137,2.029,2.464,2.607,2.286,...,2.178,2.300,2.302,2.559,2.513,2.437,2.530,2.506,2.708,2.810

In [20]:
datasets = {
    "GSE6613": gse6613,
    "GSE72267": gse72267,
    "GSE99039": gse99039,
    "GSE57475": gse57475,
    "GSE18838": gse18838
}

for name, df in datasets.items():
    print(name, "Shape:", df.shape)

GSE6613 Shape: (22283, 105)
GSE72267 Shape: (22277, 59)
GSE99039 Shape: (54675, 558)
GSE57475 Shape: (48766, 142)
GSE18838 Shape: (17881, 28)

In [21]:
for name, df in datasets.items():
    print(name, "Missing values:", df.isnull().sum().sum())

GSE6613 Missing values: 0
GSE72267 Missing values: 0
GSE99039 Missing values: 0
GSE57475 Missing values: 0
GSE18838 Missing values: 0

In [22]:
for name, df in datasets.items():
    print(name)
    print(df.index[:5])
    print()

GSE6613
Index(['1007_s_at', '1053_at', '117_at', '121_at', '1255_g_at'], dtype='str', name='ID_REF')

GSE72267
Index(['1007_s_at', '1053_at', '117_at', '121_at', '1255_g_at'], dtype='str', name='ID_REF')

GSE99039
Index(['1007_s_at', '1053_at', '117_at', '121_at', '1255_g_at'], dtype='str', name='ID_REF')

GSE57475
Index(['ILMN_1343291', 'ILMN_1343295', 'ILMN_1651199', 'ILMN_1651209',
       'ILMN_1651210'],
      dtype='str', name='ID_REF')

GSE18838
Index([2315554, 2315633, 2315674, 2315739, 2315894], dtype='int64', name='ID_REF')

In [23]:
common_genes = set(gse6613.index)

for df in datasets.values():
    common_genes = common_genes.intersection(set(df.index))

print("Number of common genes:", len(common_genes))

Number of common genes: 0

In [24]:
for name, df in datasets.items():
    print(name, "Min:", df.min().min(), "Max:", df.max().max())

GSE6613 Min: 0.1 Max: 158720.1
GSE72267 Min: 1.745663014 Max: 14.94476018
GSE99039 Min: 1.455 Max: 15.17
GSE57475 Min: 22.40097 Max: 56586.52
GSE18838 Min: -5.489131 Max: 5.8787603